server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kingconsierd/springcloud
          searchPaths: springcloudconfig
      label: master


# http\u8BF7\u6C42\u5730\u5740
# http://localhost:8888/application/profile/label

# {application}\u6620\u5C04\u5230Config\u5BA2\u6237\u7AEF\u7684spring.application.name\u5C5E\u6027
# {profile}\u6620\u5C04\u5230Config\u5BA2\u6237\u7AEF\u7684spring.profiles.active\u5C5E\u6027\uFF0C\u53EF\u4EE5\u7528\u6765\u533A\u5206\u73AF\u5883
# {label}\u6620\u5C04\u5230Git\u670D\u52A1\u5668\u7684commit id, \u5206\u652F\u540D\u79F0\u6216\u8005tag\uFF0C\u9ED8\u8BA4\u503C\u4E3Amaster
# \u5BF9\u5E94\u8D44\u6E90\u6587\u4EF6\u6620\u5C04\u5982\u4E0B:
#
# /{application}/{profile}[/{label}]
# /{application}-{profile}.yml
# /{label}/{application}-{profile}.yml
# /{application}-{profile}.properties
# /{label}/{application}-{profile}.properties